"""The examples that are broken today, so the suite can gate on anything that breaks tomorrow.

The Java and Rust examples had never been compiled by anything, and the drift that piled up
while nobody was looking is larger than one pull request can fix: about a dozen SDK changes,
spread over a hundred page-and-language pairs. A suite that is red on all of them from the day
it lands gates nothing, because nobody can tell a new break from the pile.

So the pile is written down, in `known_failures.toml`, one line per failing test with the
reason. Each listed test is expected to fail, strictly:

* it fails  -> the run stays green, and the count is reported
* it passes -> the run goes **red**, saying the entry is fixed and must be deleted
* anything not listed fails -> the run goes red, as it always would

That makes the list a ratchet. It can only shrink, and the day it is empty this module stops
mattering. It is not a way to silence a test: an entry is a promise that the *documentation*
is what is broken, which is why only the two tiers that report on documentation may be listed.
The harness's own tests, the structure checks and the plan guards can never be.

`./doctests/run.sh --write-known-failures` rewrites the file from a run, keeping the reasons
already written for entries that are still failing.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

HERE = Path(__file__).parent
FILE = HERE / "known_failures.toml"

# Only these may hold entries. A failure anywhere else is the suite breaking, not the docs.
LISTABLE = ("test_api_surface.py", "test_compile.py")

_HEADER = """# Examples that do not work today, and why. Generated by
# `./doctests/run.sh --write-known-failures`, and meant to shrink: see known_failures.py.
#
# A listed test that starts passing FAILS the run, so fixing a page means deleting its line.
# Only test_api_surface.py and test_compile.py may be listed; a failure anywhere else is the
# suite itself breaking.
"""


class KnownFailureError(Exception):
    """The list names something it may not, or something that no longer exists."""


def load(path: Path = FILE) -> dict[str, str]:
    """node id (relative to doctests/) -> reason."""
    if not path.exists():
        return {}
    raw = tomllib.loads(path.read_text(encoding="utf-8"))
    out: dict[str, str] = {}
    for node, reason in raw.get("failures", {}).items():
        if not str(reason).strip():
            raise KnownFailureError(f"{node} is listed with no reason; say what is broken.")
        if not node.startswith(LISTABLE):
            raise KnownFailureError(
                f"{node} cannot be listed. Only {', '.join(LISTABLE)} report on the "
                "documentation; everything else failing means the suite is broken, and "
                "listing it would hide that."
            )
        out[node] = str(reason)
    return out


def write(entries: dict[str, str], path: Path = FILE) -> None:
    lines = [_HEADER, "\n[failures]\n"]
    for node in sorted(entries):
        reason = entries[node].replace('"', "'").strip()
        lines.append(f'"{node}" = "{reason}"\n')
    path.write_text("".join(lines), encoding="utf-8")


def node_id(item) -> str:
    """A test's id as the file holds it: file name, then the test, whatever the run's cwd."""
    path, _, rest = str(item.nodeid).partition("::")
    return f"{Path(path).name}::{rest}" if rest else Path(path).name


_COMPILE_ERROR = re.compile(r"(docs/\S+:\d+) \(\w+ #\d+\): (.+)")
_MISSING_NAME = re.compile(r"(?:name\(s\)|method\(s\)) that this build does not have: (.+)|"
                           r"method\(s\) this SDK build does not expose: (.+)")


def reason_from(report) -> str:
    """A one-line why, taken from the failure itself, for a freshly written entry.

    The first real error, not the advice that follows it: a compile failure ends with four
    lines telling the reader where to look, and those are the same on every page.
    """
    text = str(getattr(report, "longrepr", "") or "")
    lines = [re.sub(r"^E\s+", "", line).strip() for line in text.splitlines()]
    for line in lines:
        found = _COMPILE_ERROR.search(line)
        if found:
            return f"{found.group(2)} ({found.group(1)})"[:200]
    for line in lines:
        found = _MISSING_NAME.search(line)
        if found:
            return f"uses {found.group(1) or found.group(2)}, which the SDK no longer has"[:200]
    first = next((line for line in lines if line and not line.startswith("assert")), "")
    return (first or "fails; reason not captured")[:200]


def pages_named(entries: dict[str, str]) -> set[tuple[str, str | None]]:
    """(page, language or None) for every entry, so a stale one can be spotted."""
    out: set[tuple[str, str | None]] = set()
    for node in entries:
        param = re.search(r"\[(.+)\]$", node)
        if not param:
            continue
        value = param.group(1)
        if ":" in value and value.split(":", 1)[0] in ("java", "rust"):
            lang, page = value.split(":", 1)
            out.add((page, lang))
        else:
            out.add((value, None))
    return out
